### ISSUE TITLE
Use these libraries on Arduino

### ISSUE THREAD

**Issue by TinManAkshay** [u-blox/u-connectXpress-host-library#5]
Hi.

[Not an Issue, just a Discussion]

Can these libraries be used in Arduino? I've got a board which has Ublox W152 integrated on it with UART interface. I've been looking for the AT command drivers/libraries which I can use to build my application on Arduino. End goal is to connect to a Wifi network and send or receive data via UDP.

Please let me know and any information would be highly appreciated.

Thanks,
Akshay

**Comment by leo-ublox** [comment]
> Can these libraries be used in Arduino?

No, not out of the box, you will need to port it to your platform

If you want to adapt it to Arduino, I can also suggest the following, which is also not supported, but it is designed and tested on some micro-controllers (which may include yours as well): https://github.com/u-blox/ubxlib

**Comment by TinManAkshay** [comment]
Hi @leo-ublox ,

I really appreciate for a prompt response. I've been trying to use example code"test_ati9.c" and tried porting to Arduino environment. But I am getting the following errors while compiling:

![image](https://user-images.githubusercontent.com/57913555/151053781-8ee85621-d060-4cef-b05e-7f12a86c0a08.png)

Are you familiar with this issue?

Thanks,
Akshay

**Comment by leo-ublox** [comment]
As the error says, you are missing some references. You need to include the references and where the variables are defined.

I'm afraid the best place to find resources on how to achieve that would be with the Arduino documentation/forum.

**Comment by TinManAkshay** [comment]
Hi @leo-ublox ,

Yes I have made my own code in Arduino with a reference to the test codes in your repo. 

So far, I am able to connect to Wi-Fi network and set the UDP port successfully. My next task is to receive or send UDP packets through the code. How are you controlling Tx and Rx through your program. Are you controlling Tx and Rx through AT commands or is there any other way?

Thanks,
Akshay

**Comment by leo-ublox** [comment]
Hi Akshay,

I did not fully understand your question, but I recommend section 5 of the following documentation where includes examples and explain data mode: https://www.u-blox.com/en/ubx-viewer/view/u-connectXpress-ATCommands-Manual_UBX-14044127?url=https%3A%2F%2Fwww.u-blox.com%2Fsites%2Fdefault%2Ffiles%2Fu-connectXpress-ATCommands-Manual_UBX-14044127.pdf

Furthermore, the u-blox portal (https://portal.u-blox.com/s/) would be a better place to find help on your project since the "issues" sections on GitHub has low visibility, on the portal you will have higher changes of getting help from other users.

--
BR//Leo

**Comment by TinManAkshay** [comment]
Hi Leo - 

Never mind. I figured it out. 

I have successfully developed Embedded C code around AT commands which can configure wifi network, enter Data mode and send UDP packets to the remote IP/port just like Serial.write() in Arduino.

Your libraries have been very helpful in the development of a code. Thanks a lot!! :)

-Akshay
